### PR TITLE
Fixing #171

### LINKED ISSUE #171: Can't open Microsoft Teams - blank screen
**Describe the bug**
Trying to open Microsoft Teams leaves a blank page.

**To Reproduce**
1. Open Microsoft Teams
2. That's it, a blank page should be shown (the error)

**Expected behavior**
Load normally

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.2
 - Installation package deb
 - Version teams-for-linux_0.4.0_amd64.deb

**Additional context**
Clicking on debug option I get this:

image

Any idea of what's going on? Thanks.

### PR DESCRIPTION
**Pull request by inglor**
As per the comments in #171 @IsmaelMartinez @basaas @Lomanic : 
Reverting extra logging commit and overwriting the `serviceWorker.register()` method.

I might have missed something though, please comment.

Fix #171

### CODE REVIEW

File: app/mainAppWindow/index.js [hunk 1]
```diff
@@ -13,11 +13,10 @@ let aboutBlankRequestCount = 0;
 
 let window = null;
 
-exports.onAppReady = async function onAppReady() {
+exports.onAppReady = function onAppReady() {
 	window = createWindow();
-	await clearCache(window.webContents.session);
-	await clearStorageData(window.webContents.session);
-
+	window.webContents.session.clearCache(()=> console.log("session cache cleared"));
```
Comment (IsmaelMartinez) [inline app/mainAppWindow/index.js]: We need to remove this and the next line. They where PoC that didn't solve the issue. Thanks!

Comment (inglor) [reply app/mainAppWindow/index.js]: Reverted commit b330962 and the extra line of logging.
