### PR TITLE
Add comprehensive diagnostic logging for authentication and screen sharing issues, and trying to fix the re-auth issue

### LINKED ISSUE #1357: Please sign in again? - Way to keep non-idle?
Assuming this is due to org policy around timeout. Can we do something that would keep the connection active enough to not trigger this? Native Teams or Outlook or other apps seem to be able to hold on to this. Maybe through certs or something? Pretty annoying. I understand there is only so much one can do here but asking.

### PR DESCRIPTION
**Pull request by IsmaelMartinez**
# Summary

Try to fix Microsoft Teams authentication refresh issues from #1357 by providing the missing `_tokenCache` interface to the Teams authentication provider. Should eliminate the frequent "Please sign in again" prompts after system sleep/wake cycles.

Other small fixes and enhanced login implemented as shown in the highlights

## Highlights
- **Authentication Re-login Fix**: Implemented a localStorage-backed token cache bridge to resolve persistent re-authentication issues (https://github.com/IsmaelMartinez/teams-for-linux/issues/1357), allowing the Teams authentication provider to perform silent token refreshes and maintain user sessions across restarts and sleep/wake cycles.
- **Enhanced Diagnostic Logging**: Added comprehensive diagnostic logging for both authentication and screen sharing functionalities. This includes detailed insights into token cache operations, authentication state, screen sharing stream creation, and cleanup, which will aid in diagnosing future issues like screen sharing echo (https://github.com/IsmaelMartinez/teams-for-linux/issues/1800).
- **Configuration Updates**: Updated default application settings to enable the screen sharing thumbnail to always be on top and to enable incoming call toasts by default, improving user experience.
- **Extensive Documentation**: Introduced new detailed documentation, including an issue investigation report, a Product Requirements Document (PRD), and technical research documents covering the token cache authentication fix and future secure storage plans. This provides a clear roadmap and rationale for the changes.

## Problem
- Users forced to re-authenticate frequently despite valid tokens stored in localStorage. See #1357
- Root cause: Teams auth provider missing `_tokenCache` interface to access stored tokens

## Solution
- **Token Cache Bridge**: Provides localStorage-compatible interface to Teams auth provider

## Testing
✅ **Live validated**: 20+ minute laptop sleep/wake test successful
✅ **Token persistence**: Same tokens reused across authentication events
✅ **No errors**: Zero authentication failures or login prompts

Might Fix #1357 - Superseeds #1817

### CODE REVIEW

File: app/browser/tools/reactHandler.js [hunk 1]
```diff
@@ -25,6 +31,390 @@ class ReactHandler {
...
+      console.debug(`[TOKEN_CACHE] MANUAL_INJECTION: Manually triggering token cache injection`);
+      return this._attemptTokenCacheInjection(authProvider);
+
+    } catch (error) {
+      console.error(`[TOKEN_CACHE] Error in manual token cache injection:`, error);
+      return false;
+    }
+  }
+
+  // v2.5.4: Get token cache injection status for monitoring
```
Comment (IsmaelMartinez) [inline app/browser/tools/reactHandler.js]:
```suggestion
  // v2.5.3: Get token cache injection status for monitoring
```

File: app/browser/tools/reactHandler.js [hunk 2]
```diff
@@ -25,6 +31,390 @@ class ReactHandler {
...
+      });
+      
+      console.debug(`[AUTH_DIAG] === End Token Cache Investigation ===`);
+      
+    } catch (error) {
+      console.error(`[AUTH_DIAG] Error analyzing auth provider:`, error);
+    }
+  }
+
+  // v2.5.4: Attempt to inject token cache into Teams authentication provider
```
Comment (IsmaelMartinez) [inline app/browser/tools/reactHandler.js]:
```suggestion
  // v2.5.3: Attempt to inject token cache into Teams authentication provider
```

File: app/browser/tools/reactHandler.js [hunk 3]
```diff
@@ -25,6 +31,390 @@ class ReactHandler {
...
+        return false;
+      }
+
+    } catch (error) {
+      console.error(`[TOKEN_CACHE] INJECTION_ERROR: Error during token cache injection:`, error);
+      return false;
+    }
+  }
+
+  // v2.5.4: Validate token cache injection was successful
```
Comment (IsmaelMartinez) [inline app/browser/tools/reactHandler.js]:
```suggestion
  // v2.5.3: Validate token cache injection was successful
```

File: app/browser/tools/reactHandler.js [hunk 4]
```diff
@@ -25,6 +31,390 @@ class ReactHandler {
...
+        return false;
+      }
+
+    } catch (error) {
+      console.error(`[TOKEN_CACHE] VALIDATION_ERROR: Error during validation:`, error);
+      return false;
+    }
+  }
+
+  // v2.5.4: Validate existing token cache interface
```
Comment (IsmaelMartinez) [inline app/browser/tools/reactHandler.js]:
```suggestion
  // v2.5.3: Validate existing token cache interface
```

File: app/browser/tools/tokenCache.js [hunk 5]
```diff
@@ -0,0 +1,654 @@
+// Teams Token Cache Bridge
+// v2.5.4: Implement localStorage-compatible token cache interface for Teams authentication provider
```
Comment (IsmaelMartinez) [inline app/browser/tools/tokenCache.js]:
```suggestion
// v2.5.3: Implement localStorage-compatible token cache interface for Teams authentication provider
```

File: app/config/index.js [hunk 6]
```diff
@@ -297,7 +297,7 @@ function extractYargConfig(configObject, appVersion) {
           "Use windows platform information in chromium. This is helpful if MFA app does not support Linux.",
       },
       enableIncomingCallToast: {
-        default: false,
+        default: true,
```
Comment (IsmaelMartinez) [inline app/config/index.js]:
```suggestion
        default: false,
```

File: docs-site/docs/ai-research/token-cache-authentication-investigation.md [hunk 7]
```diff
@@ -0,0 +1,213 @@
...
+3. Graceful fallback mechanisms
+
+## Implementation Tasks & Spikes
+
+### Phase 1: Token Cache Bridge (Quick Win)
+- [ ] **SPIKE**: Analyze exact cache interface expected by Teams auth provider
+- [ ] **TASK**: Implement localStorage-backed cache bridge
+- [ ] **TASK**: Inject cache bridge into auth provider at runtime
+- [ ] **TASK**: Test silent token refresh functionality
+- [ ] **TASK**: Add comprehensive logging for cache operations
```
Comment (IsmaelMartinez) [inline docs-site/docs/ai-research/token-cache-authentication-investigation.md]:
```suggestion
- [x] **SPIKE**: Analyze exact cache interface expected by Teams auth provider
- [x] **TASK**: Implement localStorage-backed cache bridge
- [x] **TASK**: Inject cache bridge into auth provider at runtime
- [x] **TASK**: Test silent token refresh functionality
- [x] **TASK**: Add comprehensive logging for cache operations
```

File: app/browser/tools/reactHandler.js [hunk 8]
```diff
@@ -1,10 +1,16 @@
+// v2.5.4: Import token cache for authentication provider integration
```
Comment (IsmaelMartinez) [inline app/browser/tools/reactHandler.js]:
```suggestion
// v2.5.3: Import token cache for authentication provider integration
```

File: app/browser/tools/reactHandler.js [hunk 9]
```diff
@@ -25,6 +31,390 @@ class ReactHandler {
     return teams2CoreServices?.clientPreferences?.clientPreferences;
   }
 
+  // v2.5.4: Public method to manually trigger token cache injection
```
Comment (IsmaelMartinez) [inline app/browser/tools/reactHandler.js]:
```suggestion
  // v2.5.3: Public method to manually trigger token cache injection
```
